trigger:
- master

pool:
  name: shiva

steps:
- script: echo welcome to shiva marrage
  displayName: stage 1
- script: echo welocme to shiva nishu marriage
  displayName: stage 2
- script: echo welcome to shiva nishu baby bdy
  displayName: stage 3
